version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - '5672:5672' #AMQP port (Celery broker)
      - '15672:15672' #management UI -> http://localhost:15672 (guest/guest)

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    
  worker:
    build: .
    command: >
      celery -A workers.celery_app worker
      --loglevel=info
      --concurrency=4
      --queues=usecase_queue
      --hostname=worker@%h
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    #scale with: docker compose up --scale worker=4

  flower:
    build: .
    command: celery -A workers.celery_app flower --port=5555
    ports:
      - '5555:5555' # Flower UI -> http://localhost:5555
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
      REDIS_URL: redis://redis:6379/0
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started

  usecase:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - '8001:8001'
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
      REDIS_URL: redis://redis:6379/0
      USE_WORKER_QUEUE: 'true'
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy




